version: "2"
services:
  mysql: 
    image: 'mysql:5.6.35'
    environment:
      MYSQL_ROOT_PASSWORD: "tu_password"
      MYSQL_DATABASE: "tu_bd"
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  php: 
    build: docker/dockerfiles/php/
    links: 
      - mysql:mysqldb
    volumes: 
      - ./:/var/www/html
  apache: 
    build: docker/dockerfiles/apache/ 
    links: 
      - php:phpfpm 
    volumes: 
      - ./:/var/www/html
    ports:
      - 9000:80